### SEND FETCH / REQUEST
http://localhost:3000/

### SEND FETCH SONGS REQUEST
GET http://localhost:3000/songs

### SEND FETCH SONG REQUEST
GET http://localhost:3000/songs/1

### SEND CREATE SONG REQUEST
POST http://localhost:3000/songs
Content-Type: application/json

{
    "title": "Lasting Lover",
    "artists": ["sigla"],
    "releasedDate": "2022-09-29",
    "duration": "02:34",
    "lyrics": "I Dunno what I'm singing about no doubt its a load of crap anyway..."
}

### SEND UPDATE SONG REQUEST
PUT http://localhost:3000/songs/1

### SEND DELETE SONG REQUEST
DELETE http://localhost:3000/songs/1